### ISSUE TITLE
Error running runmlb.py

### ISSUE THREAD

**Issue by obecerra-dimeline** [Colin-Hanley1/MLB-Model#1]
I receive the following error:

```
$python3 runmlb.py    
Home Team: Padres
Away Team: Dodgers
Traceback (most recent call last):
  File "./MLB-Model/MLBModel/runmlb.py", line 48, in <module>
    tester = torch.from_numpy(matchup(t1, t2)).float()
                              ^^^^^^^^^^^^^^^
  File "./MLB-Model/MLBModel/runmlb.py", line 19, in matchup
    index1 = df[df['Team'] == home].index[0]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "./mlb-model/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
           ^^^^^^^^^^^^
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by Colin-Hanley1** [comment]
The model is currently very specific with capitalization and naming of the teams on input. I will add a list of the specific names needed. Working on making the code more flexible currently!

**Comment by Colin-Hanley1** [comment]
Issue should be fixed now
